### ISSUE TITLE
Results are not as expected

### ISSUE THREAD

**Issue by ilaurillard** [busterc/merge_map_null_safety#1]
```
  print(mergeMap([
    {
      'a': {
        'b': 1,
      }
    },
    {
      'a': {
        'c': 1,
      }
    }
  ]));
```

gives me a result:

{a: {c: 1}}

Is this a bug?

**Comment by busterc** [comment]
This is the expected outcome, because as the README states, `mergeMap()` is  
> Equivalent to [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) in JS.

Meaning, it performs a shallow merge.

However, it's easy to wrap `mergeMap()` with your own implementation of (recursive) deep merging. Or you can use another plugin with the capability such as [normalize->deepMerge()](https://pub.dev/documentation/normalize/latest/utils/deepMerge.html) (albeit with several other features you may not need)

Good luck!
